import { Product } from '../types';

// African Currencies
export const CURRENCIES = [
  { code: 'USD', symbol: '$', rate: 1, name: 'US Dollar' },
  { code: 'NGN', symbol: '₦', rate: 1500, name: 'Nigerian Naira' },
  { code: 'ZAR', symbol: 'R', rate: 19, name: 'South African Rand' },
  { code: 'KES', symbol: 'KSh', rate: 130, name: 'Kenyan Shilling' },
  { code: 'EGP', symbol: 'E£', rate: 48, name: 'Egyptian Pound' },
  { code: 'GHS', symbol: 'GH₵', rate: 14, name: 'Ghanaian Cedi' },
  { code: 'ETB', symbol: 'Br', rate: 56, name: 'Ethiopian Birr' },
];

// Sample Commodities
export const COMMODITIES: Product[] = [
  {
    id: '1',
    name: "UNFPA Emergency Kit",
    category: "Emergency Kits",
    categoryLabel: "Emergency",
    sku: "EMT-UNFPA-001",
    price: 149.99,
    stock: 45,
    shape: 'kit',
    description: "Comprehensive UNFPA emergency response kit for maternal health and emergency care. Contains essential supplies for safe delivery, post-rape treatment, and emergency obstetric care in field conditions.",
    usage: "For emergency maternal health care and GBV response in field conditions. Follow UNFPA guidelines for deployment.",
    dosage: "N/A - Emergency use only. Single patient use items.",
    included: "Emergency delivery kit, Post-rape treatment kit, Hygiene supplies, Medical instruments, Emergency blankets",
    storage: "Store at 15-25°C (59-77°F)",
    shelfLife: "24 Months",
    useCase: "Emergency Response",
    list: ["Emergency delivery kit", "Post-rape treatment kit", "Hygiene supplies", "Medical instruments", "Emergency blankets", "Sterile gloves", "Absorbent pads"],
    weight: "12.5 kg",
    dimensions: "60x40x30 cm"
  },
  {
    id: '2',
    name: "Medical Examination Gloves (Box of 100)",
    category: "PPE",
    categoryLabel: "Protection",
    sku: "PPE-GLV-100",
    price: 45.99,
    stock: 120,
    shape: 'glove',
    description: "Nitrex medical examination gloves, nitrile construction, powder-free, blue color. Superior chemical resistance and tactile sensitivity.",
    usage: "Medical examinations, patient care, laboratory work, wound dressing, and cleaning procedures.",
    dosage: "Single use only. Dispose after each patient contact. Do not wash or reuse.",
    included: "100 Nitrile Gloves, Powder-free formulation",
    storage: "Keep in a cool, dry place",
    shelfLife: "60 Months",
    useCase: "Protection",
    list: ["100 Nitrile Gloves", "Powder-free formulation", "Latex-free", "Chemical resistant", "Ambidextrous design"],
    weight: "0.8 kg",
    dimensions: "24x12x8 cm"
  },
  {
    id: '3',
    name: "Medical Safety Sharps Box",
    category: "First Aid",
    categoryLabel: "Safety",
    sku: "SAF-SHP-001",
    price: 89.99,
    stock: 8,
    shape: 'kit',
    description: "WHO-approved safety box for sharps disposal and medical waste containment. Rigid puncture-resistant construction with secure locking mechanism.",
    usage: "Safe disposal of needles, syringes, lancets, and other sharps in medical settings and field hospitals.",
    dosage: "Dispose when 3/4 full. Do not overfill. Seal permanently when full.",
    included: "Safety Box 5L capacity, Locking mechanism",
    storage: "Store in a secure location",
    shelfLife: "Indefinite",
    useCase: "Safety",
    list: ["Safety Box 5L capacity", "Locking mechanism", "Biohazard warning markings", "Incineration-ready cardboard", "Fill-level indicator"],
    weight: "0.5 kg",
    dimensions: "30x20x15 cm"
  },
  {
    id: '4',
    name: "Safety Gumboots with Steel Toe",
    category: "PPE",
    categoryLabel: "Protection",
    sku: "PPE-BOOT-001",
    price: 175.00,
    stock: 32,
    shape: 'kit',
    description: "Green PVC plastic safety gumboots with steel toe caps for medical and industrial use. Chemical resistant with slip-resistant soles.",
    usage: "Foot protection in medical, laboratory, contaminated environments, and wet conditions.",
    dosage: "N/A - Reusable. Clean and disinfect after each use in contaminated areas.",
    included: "1 Pair Safety Boots, Steel toe cap protection",
    storage: "Clean and dry after use",
    shelfLife: "Indefinite",
    useCase: "Protection",
    list: ["1 Pair Safety Boots", "Steel toe cap protection", "PVC construction", "Slip-resistant sole", "Chemical resistant material", "Steel midsole option"],
    weight: "2.2 kg",
    dimensions: "40x30x15 cm"
  },
  {
    id: '5',
    name: "Multi-Parameter Patient Monitor",
    category: "Diagnostics",
    categoryLabel: "Monitoring",
    sku: "DIA-MON-001",
    price: 2499.99,
    stock: 15,
    shape: 'kit',
    description: "Advanced patient monitoring system with 12.1-inch display. Monitors ECG, SpO2, NIBP, temperature, and respiration simultaneously.",
    usage: "Continuous monitoring of vital signs in ICU, emergency, and clinical settings.",
    dosage: "Continuous monitoring as clinically indicated. Alarm limits adjustable per patient needs.",
    included: "Monitor Unit, ECG Cable with leads, SpO2 Finger Probe",
    storage: "Store in a dry, dust-free environment",
    shelfLife: "10 Years",
    useCase: "Monitoring",
    list: ["Monitor Unit", "ECG Cable with leads", "SpO2 Finger Probe", "NIBP Cuff (adult)", "Temperature Probe", "Power Adapter", "Rechargeable Battery", "Stand/Wall Mount"],
    weight: "5.5 kg",
    dimensions: "35x30x25 cm"
  },
  {
    id: '6',
    name: "Emergency Field Support Cot",
    category: "Emergency Kits",
    categoryLabel: "Support",
    sku: "EMT-COT-001",
    price: 329.99,
    stock: 18,
    shape: 'kit',
    description: "Portable field support cot for emergency medical response and disaster relief. Lightweight aluminum frame with durable fabric.",
    usage: "Patient transport, temporary bedding in field hospitals, emergency evacuation, and disaster response.",
    dosage: "N/A - Weight capacity 300 lbs. Clean and disinfect between patients.",
    included: "Foldable Cot Frame, Durable fabric mattress",
    storage: "Fold and store in carry bag",
    shelfLife: "Indefinite",
    useCase: "Support",
    list: ["Foldable Cot Frame", "Durable fabric mattress", "Carry Bag with straps", "IV Pole Attachment", "Patient Safety Straps", "Side rails"],
    weight: "8.0 kg",
    dimensions: "190x70x40 cm"
  },
  {
    id: '7',
    name: "Biomedical Consumables Pack",
    category: "PPE",
    categoryLabel: "Laboratory",
    sku: "BIO-CON-001",
    price: 124.99,
    stock: 45,
    shape: 'kit',
    description: "Essential biomedical laboratory consumables for diagnostic and research use. Sterile single-use items.",
    usage: "Laboratory diagnostics, sample collection, cell culture, and biomedical research applications.",
    dosage: "Single use only. Sterile until opened. Dispose according to biohazard protocols.",
    included: "Pipette Tips, Test Tubes, Petri Dishes",
    storage: "Store in a sterile environment",
    shelfLife: "36 Months",
    useCase: "Laboratory",
    list: ["Pipette Tips (various sizes)", "Test Tubes (sterile)", "Petri Dishes", "Microscope Slides", "Collection Vials", "Transfer Pipettes", "Microcentrifuge Tubes"],
    weight: "1.5 kg",
    dimensions: "30x20x20 cm"
  },
  {
    id: '8',
    name: "Oxygen Concentrator 5L",
    category: "Diagnostics",
    categoryLabel: "Respiratory",
    sku: "OXY-CON-005",
    price: 1899.99,
    stock: 6,
    shape: 'kit',
    description: "5-liter medical oxygen concentrator for respiratory therapy. Provides continuous oxygen flow with 93% ± 3% purity.",
    usage: "Provides supplemental oxygen therapy for patients with COPD, pneumonia, and respiratory distress.",
    dosage: "Adjust flow rate 1-5 L/min as prescribed by physician. Continuous operation capable.",
    included: "Oxygen Concentrator Unit, Nasal Cannula",
    storage: "Keep in a well-ventilated area",
    shelfLife: "5 Years",
    useCase: "Respiratory",
    list: ["Oxygen Concentrator Unit", "Nasal Cannula (adult)", "Humidifier Bottle", "Air Filter (spare)", "Power Cord", "User Manual", "Oxygen tubing"],
    weight: "14.5 kg",
    dimensions: "50x30x60 cm"
  },
  {
    id: '9',
    name: "Nasal High Flow Therapy System",
    category: "Emergency Kits",
    categoryLabel: "Respiratory",
    sku: "OXY-NHF-001",
    price: 2899.99,
    stock: 8,
    shape: 'kit',
    description: "High flow nasal cannula system for oxygen therapy with integrated heated humidification. Flow rates up to 60 L/min.",
    usage: "Deliver high flow oxygen therapy for acute respiratory failure, providing precise FiO2 and humidification.",
    dosage: "Flow rates 2-60 L/min, FiO2 21-100% as clinically indicated. Temperature adjustable 31-37°C.",
    included: "High Flow Generator, Heated Humidifier Chamber",
    storage: "Store in a clean, dry place",
    shelfLife: "5 Years",
    useCase: "Respiratory",
    list: ["High Flow Generator", "Heated Humidifier Chamber", "Nasal Cannula Set (various sizes)", "Air/Oxygen Blender", "Tubing circuit", "Power cord"],
    weight: "6.5 kg",
    dimensions: "40x30x30 cm"
  },
  {
    id: '10',
    name: "Water Quality Testing Kit",
    category: "Diagnostics",
    categoryLabel: "Safety",
    sku: "WAT-TEST-001",
    price: 299.99,
    stock: 25,
    shape: 'kit',
    description: "Professional water testing kit for bacteriological and chemical analysis. WHO-compliant testing methods.",
    usage: "Field testing of drinking water for bacterial contamination, pH, chlorine, and chemical parameters.",
    dosage: "Test as per WHO guidelines. Follow incubation times for bacteriological tests (18-24 hours).",
    included: "Test Chambers, Reagent Tablets",
    storage: "Keep reagents in a cool, dark place",
    shelfLife: "24 Months",
    useCase: "Safety",
    list: ["Test Chambers (sterile)", "Reagent Tablets (various tests)", "Comparator colorimeter", "Thermometer", "pH Test Strips", "Bacteria Test Vials", "Carrying Case", "Instruction Manual"],
    weight: "2.5 kg",
    dimensions: "35x25x15 cm"
  },
  {
    id: '11',
    name: "Laboratory Centrifuge Rotanta 460",
    category: "Diagnostics",
    categoryLabel: "Laboratory",
    sku: "LAB-CEN-460",
    price: 5499.99,
    stock: 4,
    shape: 'kit',
    description: "High-capacity refrigerated centrifuge for blood processing and laboratory diagnostics. Capacity up to 4 x 750ml.",
    usage: "Separation of blood components, urine sediment preparation, and laboratory sample processing.",
    dosage: "Variable speed up to 6,000 rpm. Temperature control -10°C to +40°C. Program as per sample requirements.",
    included: "Centrifuge Unit, Swing-out Rotor",
    storage: "Keep on a stable, level surface",
    shelfLife: "15 Years",
    useCase: "Laboratory",
    list: ["Centrifuge Unit", "Swing-out Rotor", "Buckets (4x)", "Lid with safety lock", "Power Cord", "User Manual", "Refrigeration system"],
    weight: "115.0 kg",
    dimensions: "70x70x50 cm"
  },
  {
    id: '12',
    name: "Medical Refrigerator 260L",
    category: "Emergency Kits",
    categoryLabel: "Cold Chain",
    sku: "REF-MED-260",
    price: 1899.99,
    stock: 9,
    shape: 'kit',
    description: "WHO-PQS compliant medical refrigerator for vaccine and medicine storage. 260L capacity with temperature monitoring.",
    usage: "Cold chain storage for vaccines, medicines, blood products, and temperature-sensitive medical supplies.",
    dosage: "Maintain 2-8°C for vaccines. Monitor temperature continuously. 24/7 operation required.",
    included: "Refrigerator Unit, Wire Storage Baskets",
    storage: "24/7 power supply required",
    shelfLife: "10 Years",
    useCase: "Cold Chain",
    list: ["Refrigerator Unit", "Wire Storage Baskets (4x)", "Digital Temperature Monitor", "Ice Pack Freezing Compartment", "Door Lock", "Power Cord", "Voltage stabilizer"],
    weight: "85.0 kg",
    dimensions: "60x60x160 cm"
  },
  {
    id: '13',
    name: "Portable Suction Unit ConCoe",
    category: "Emergency Kits",
    categoryLabel: "Emergency",
    sku: "SUC-CON-001",
    price: 449.99,
    stock: 22,
    shape: 'kit',
    description: "Portable medical suction unit for airway clearance and surgical suction. Battery operated with AC adapter.",
    usage: "Emergency airway suction, surgical suction, and patient secretion management in field and hospital settings.",
    dosage: "Adjust suction pressure 80-200 mmHg as clinically indicated. 30L/min flow rate.",
    included: "Suction Unit, Collection Canister",
    storage: "Keep battery charged",
    shelfLife: "5 Years",
    useCase: "Emergency Response",
    list: ["Suction Unit", "Collection Canister (1L)", "Suction Tubing (2m)", "Handpiece with tip", "Power Adapter", "Rechargeable Battery Pack", "Carrying Case", "Spare filters"],
    weight: "4.5 kg",
    dimensions: "35x20x25 cm"
  }
];

// Sample Orders
export const INITIAL_ORDERS = [
  {
    id: 'ORD-2024-001',
    country: 'Nigeria',
    items: [
      { commodity: COMMODITIES[0], qty: 50 },
      { commodity: COMMODITIES[4], qty: 100 }
    ],
    priority: 'High',
    status: 'Submitted',
    pateoRef: 'PATEO-NG-2024-0156',
    pateoFile: 'PATEO_Nigeria_Jan2024.pdf',
    date: '2024-01-15',
    notes: 'Urgent need for outbreak response',
    labReviewedBy: null,
    labReviewDate: null,
    oslApprovedBy: null,
    oslApproveDate: null
  },
  {
    id: 'ORD-2024-002',
    country: 'Kenya',
    items: [
      { commodity: COMMODITIES[1], qty: 30 },
      { commodity: COMMODITIES[2], qty: 10 }
    ],
    priority: 'Medium',
    status: 'Submitted',
    pateoRef: 'PATEO-KE-2024-0089',
    pateoFile: 'PATEO_Kenya_Jan2024.pdf',
    date: '2024-01-14',
    notes: 'Quarterly restock',
    labReviewedBy: null,
    labReviewDate: null,
    oslApprovedBy: null,
    oslApproveDate: null
  },
  {
    id: 'ORD-2024-003',
    country: 'Ghana',
    items: [{ commodity: COMMODITIES[6], qty: 20 }],
    priority: 'Low',
    status: 'Forwarded to OSL',
    pateoRef: 'PATEO-GH-2024-0034',
    pateoFile: 'PATEO_Ghana_Jan2024.pdf',
    date: '2024-01-12',
    notes: 'Standard order',
    labReviewedBy: 'Dr. Amara Osei',
    labReviewDate: '2024-01-13',
    oslApprovedBy: null,
    oslApproveDate: null
  },
  {
    id: 'ORD-2024-004',
    country: 'Nigeria',
    items: [
      { commodity: COMMODITIES[3], qty: 200 },
      { commodity: COMMODITIES[7], qty: 50 }
    ],
    priority: 'Medium',
    status: 'Forwarded to OSL',
    pateoRef: 'PATEO-NG-2024-0157',
    pateoFile: 'PATEO_Nigeria_Jan2024_2.pdf',
    date: '2024-01-10',
    notes: 'Lab expansion supplies',
    labReviewedBy: 'Dr. Amara Osei',
    labReviewDate: '2024-01-11',
    oslApprovedBy: null,
    oslApproveDate: null
  },
  {
    id: 'ORD-2024-005',
    country: 'South Africa',
    items: [{ commodity: COMMODITIES[0], qty: 100 }],
    priority: 'High',
    status: 'Approved',
    pateoRef: 'PATEO-ZA-2024-0201',
    pateoFile: 'PATEO_SouthAfrica_Jan2024.pdf',
    date: '2024-01-08',
    notes: 'Surge capacity',
    labReviewedBy: 'Dr. Kofi Mensah',
    labReviewDate: '2024-01-09',
    oslApprovedBy: 'Marie Laurent',
    oslApproveDate: '2024-01-10'
  },
  {
    id: 'ORD-2024-006',
    country: 'Kenya',
    items: [{ commodity: COMMODITIES[4], qty: 500 }],
    priority: 'Low',
    status: 'Shipped',
    pateoRef: 'PATEO-KE-2024-0088',
    pateoFile: 'PATEO_Kenya_Dec2023.pdf',
    date: '2024-01-05',
    notes: 'Annual PPE restock',
    labReviewedBy: 'Dr. Amara Osei',
    labReviewDate: '2024-01-06',
    oslApprovedBy: 'Jean Pierre',
    oslApproveDate: '2024-01-07',
    shipmentTracking: 'DHL-9876543210'
  },
];

export const TOP_NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'products', label: 'Products' },
  { id: 'supply-chain', label: 'Supply Chain' },
  { id: 'laboratory', label: 'Laboratory' },
  { id: 'admin', label: 'Admin' },
];

export const SIDEBAR_NAV_ITEMS: Record<string, { id: string, label: string, icon?: string }[]> = {
  'dashboard': [
    { id: 'overview', label: 'Overview' },
    { id: 'analytics', label: 'Analytics' },
  ],
  'products': [
    { id: 'catalog', label: 'Catalog' },
    { id: 'categories', label: 'Categories' },
  ],
  'supply-chain': [
    { id: 'orders', label: 'Orders' },
    { id: 'drafts', label: 'Draft Orders' },
    { id: 'osl-operations', label: 'OSL Operations' },
    { id: 'inventory', label: 'Inventory' },
    { id: 'warehouse', label: 'Warehouse' },
  ],
  'laboratory': [
    { id: 'lab-dashboard', label: 'Lab Dashboard' },
    { id: 'controls', label: 'Controls' },
  ],
  'admin': [
    { id: 'admin-dashboard', label: 'Admin Dashboard' },
    { id: 'users', label: 'User Management' },
    { id: 'settings', label: 'Settings' },
  ],
};

export const getNavItems = (role: string) => {
  // This function is now used for Top Nav
  const baseItems = [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'products', label: 'Products' },
    { id: 'supply-chain', label: 'Supply Chain' },
  ];

  if (role === 'Laboratory Team' || role === 'Super Admin') {
    baseItems.push({ id: 'laboratory', label: 'Laboratory' });
  }

  if (role === 'Super Admin') {
    baseItems.push({ id: 'admin', label: 'Admin' });
  }

  return baseItems;
};
